### ISSUE TITLE
Choropleth shows single colour when "values" range is 0 to 370 for e.g.

### ISSUE THREAD

**Issue by LoveenDyall** [Ohtsu/o2-chart-lib#2]
When choropleth graph data is loaded, if the "data" array has a range of greater than say 20, then the choropleth shows a single colour

**Comment by LoveenDyall** [comment]
[o2chart.zip](https://github.com/Ohtsu/o2-chart-lib/files/1624262/o2chart.zip)

-- fix

**Comment by Ohtsu** [comment]
Thank you so much for your help.
